### ISSUE TITLE
Add the capability to delete versions

### ISSUE THREAD

**Issue by chauncey-garrett** [cimon-io/ansible-role-asdf#10]
The capability to delete versions would be useful. _i.e._,

```
      - name: nodejs
        repository: "https://github.com/asdf-vm/asdf-nodejs"
        versions:
          - 10.17.0
          - 12.13.1
        delete_versions:
          - 8.16.2 # v8 EOL 2019-12-31
```
