### ISSUE TITLE
Error: One or more supplied key could not be found in the database.

### ISSUE THREAD

**Issue by mazz-seven** [cimon-io/ansible-role-asdf#12]
Hey, 
Thank you for open source this role.
I'm trying to install elixir and erlang on a docker container (Ubuntu)
But I'm getting this error: One or more supplied key could not be found in the database.
```
- hosts: docker_container
  become: true
  gather_facts: false
  roles:
  - role: ansible-role-asdf
    asdf_plugins:
      - name: "erlang"
      - name: "elixir"
 pre_tasks:
    - name: Installing Python3
      raw: apt-get update && apt-get -y install python3-minimal
    # action: setup will gather facts
    - name: Gathering Facts
      action: setup
```
