### ISSUE TITLE
Basic example throws error at TASK [ansible-role-asdf : erlang - Install plugin]

### ISSUE THREAD

**Issue by DriesCruyskens** [cimon-io/ansible-role-asdf#26]
I'm trying out this role on an Ubuntu 2022 arm64 and have a very simple playbook:
```yaml
- hosts: all
  name: configure-vm
  roles:
    - role: ansible-role-asdf
      asdf_plugins:
      - name: "erlang"
        versions: [ "18.3", "20.1" ]
        global: "20.1"
      - name: "elixir"
        versions: "1.3.1"
```

throws:
```shell
...
│ TASK [ansible-role-asdf : Create configuration script]
│ *************************
│ changed: [__]
│ 
│ TASK [ansible-role-asdf : include_tasks]
│ ***************************************
│ included:
│ /Users/driescruyskens/.ansible/roles/ansible-role-asdf/tasks/plugin.yml for
│ __ => (item={'name': 'erlang', 'versions': ['18.3', '20.1'],
│ 'global': '20.1'})
│ included:
│ /Users/driescruyskens/.ansible/roles/ansible-role-asdf/tasks/plugin.yml for
│ __ => (item={'name': 'elixir', 'versions': '1.3.1'})
│ 
│ TASK [ansible-role-asdf : erlang - Install plugin]
│ *****************************
│ fatal: [__]: FAILED! => {"changed": true, "cmd": ["/bin/bash",
│ "-lc", "asdf plugin-add erlang "], "delta": "0:00:00.017269", "end":
│ "2023-05-03 16:07:58.123151", "msg": "non-zero return code", "rc": 127,
│ "start": "2023-05-03 16:07:58.105882", "stderr": "/bin/bash: line 1: asdf:
│ command not found", "stderr_lines": ["/bin/bash: line 1: asdf: command not
│ found"], "stdout": "", "stdout_lines": []}

```

When I ssh into the server and run `asdf plugin-add erlang` manually it installs without problems...
