### ISSUE TITLE
'set group permissions' task recursively crashes for crystal lang

### ISSUE THREAD

**Issue by jphaward** [cimon-io/ansible-role-asdf#27]
Within tasks//plugins.yml there is the following set group permissions task:

```
- name: "set group permissions"
  become: yes
  file:
    path: "{{ asdf_dir }}"
    owner: "{{ asdf_user }}"
    group: "{{ asdf_group }}"
    state: directory
    recurse: yes
```

I am using this to deploy crystal lang via asdf ("https://github.com/asdf-community/asdf-crystal.git") but this task is causing issues once crystal has been installed. This is because within the crystal binary there is a sym link to the parent directory, so when the group permissions task recursively goes through the files it becomes stuck in an infinite loop and crashes.

```
[server crystal]# pwd
<dir>/.asdf/installs/crystal/1.8.1/lib/crystal
[server crystal]# ll
total 376
lrwxrwxrwx. 1 user group      9 Apr 20 14:12 bin -> ../../bin
lrwxrwxrwx. 1 user group      2 Apr 20 14:12 lib -> ..
-rw-r-----. 1 user group  382312 Apr 20 14:12 libgc.a
```

```
fatal: [server]: FAILED! => {"changed": false, "msg": "failed to retrieve selinux context", "path": "<dir>/.asdf/installs/crystal/1.8.1/lib/crystal/../crystal/../crystal/../crystal/../crystal/../crystal/../crystal/../crystal/../" etc etc etc etc
```

This Ansible file task does have a "follow" option, which by default is "yes", but if set to "No" it does not follow symlinks and the task executes successfully.

```
- name: "set group permissions"
  become: yes
  file:
    path: "{{ asdf_dir }}"
    owner: "{{ asdf_user }}"
    group: "{{ asdf_group }}"
    state: directory
    recurse: yes
    follow: no
```

Would this have any negative effect any other use cases or would this be able to be added as a failsafe? Or perhaps var could be added to toggle this.
